// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/get_records.proto

package partitions_searcher

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetRecordsServiceClient is the client API for GetRecordsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetRecordsServiceClient interface {
	Get(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error)
}

type getRecordsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetRecordsServiceClient(cc grpc.ClientConnInterface) GetRecordsServiceClient {
	return &getRecordsServiceClient{cc}
}

func (c *getRecordsServiceClient) Get(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error) {
	out := new(GetRecordsResponse)
	err := c.cc.Invoke(ctx, "/partitions_searcher.GetRecordsService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetRecordsServiceServer is the server API for GetRecordsService service.
// All implementations must embed UnimplementedGetRecordsServiceServer
// for forward compatibility
type GetRecordsServiceServer interface {
	Get(context.Context, *GetRecordsRequest) (*GetRecordsResponse, error)
	mustEmbedUnimplementedGetRecordsServiceServer()
}

// UnimplementedGetRecordsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetRecordsServiceServer struct {
}

func (UnimplementedGetRecordsServiceServer) Get(context.Context, *GetRecordsRequest) (*GetRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGetRecordsServiceServer) mustEmbedUnimplementedGetRecordsServiceServer() {}

// UnsafeGetRecordsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetRecordsServiceServer will
// result in compilation errors.
type UnsafeGetRecordsServiceServer interface {
	mustEmbedUnimplementedGetRecordsServiceServer()
}

func RegisterGetRecordsServiceServer(s grpc.ServiceRegistrar, srv GetRecordsServiceServer) {
	s.RegisterService(&GetRecordsService_ServiceDesc, srv)
}

func _GetRecordsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetRecordsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partitions_searcher.GetRecordsService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetRecordsServiceServer).Get(ctx, req.(*GetRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetRecordsService_ServiceDesc is the grpc.ServiceDesc for GetRecordsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetRecordsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "partitions_searcher.GetRecordsService",
	HandlerType: (*GetRecordsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GetRecordsService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/get_records.proto",
}
